labels:
  - name: exercise
    color: "#3F9E78"
  - name: proof
    color: "#1E4278"
  - name: style
    color: "#D9D186"
  - name: error
    color: "#D90D0D"
  - name: citation
    color: "#542678"

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions: null
