title: qwinters
logo: /assets/img/profile-pic.png
description: Math => Software => Math; with a little bit of Magic between
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: true
  owner_url: "https://github.com/qwinters"
