name: Update PDFs in GitHub branch (not main) 
on:
  push:
    branches-ignore: [main]
jobs:
  build:
    name: Update lecture notes on website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: github_checkout
        uses: actions/checkout@v2
      - name: Lint LaTeX code using chktex 
        id: lint_latex
        uses: j2kun/chktex-action@main
      - name: Compile LaTeX documents from source
        id: compile_latex
        uses: xu-cheng/texlive-action/full@v1
        with: 
          run: sh .github/scripts/compile.sh
      - name: Commit built PDFs to the main branch 
        id: commit_latex
        shell: bash 
        run: sh .github/scripts/commit.sh

