name: Update lecture notes on website
on:
  push:
    branches: [main]
jobs:
  build:
    name: Update lecture notes on website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: github_checkout
        uses: actions/checkout@v2
      - name: Create issues from TODO comments in code
        id: todo_to_issue
        uses: alstr/todo-to-issue-action@v4.5
        with:
          AUTO_ASSIGN: true
      - name: Lint LaTeX code using chktex 
        id: lint_latex
        uses: j2kun/chktex-action@main
      - name: Compile LaTeX documents from source
        id: compile_latex
        uses: xu-cheng/texlive-action/full@v1
        with: 
          run: sh .github/scripts/compile.sh
      - name: Encrypt / prepare PDFs and homepage for website
        id: prepare_website
        shell: bash 
        runs: sh .github/scripts/update-website.sh
      - name: Deploy updates to GitHub pages 
        id: deploy_gh_pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with: 
          branch: website
          folder: website
